service: base-template

frameworkVersion: "3"

plugins:
  - serverless-bundle

provider:
  name: aws
  profile: sls
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  example:
    handler: src/handlers/example.handler
    events:
      - http:
          method: GET
          path: /example
